/**
 * Property 7: assessmentToSession / sessionToAssessment Round Trip
 * Validates: Requirements 22.2
 *
 * For arbitrary Assessment objects, verify that
 * sessionToAssessment(assessmentToSession(a)) preserves:
 *   - currentScore (next in session)
 *   - previousScore (prev in session)
 *   - justification (notes in session)
 *   - questionText (the session score key)
 *
 * Note: id, reviewPeriod, engineerName, managerName are also preserved exactly.
 * dateCompleted is NOT preserved because sessionToAssessment sets it to now().
 * oneOnOneTopics are NOT preserved (session has no topics field).
 * categoryId is regenerated by sessionToAssessment (positional).
 */

import { describe, it, expect } from 'vitest'
import * as fc from 'fast-check'
import {
  assessmentToSession,
  sessionToAssessment,
  withDerivedAverages,
  type Assessment,
  type AssessmentCategory,
  type AssessmentQuestion,
} from '../mappers'

// ── Arbitraries ──────────────────────────────────────────────────────────────

const scoreArb = fc.integer({ min: 1, max: 5 })

// Question texts must be unique within a category (they are the session score keys)
const uniqueQuestionTextsArb = fc
  .array(fc.string({ minLength: 1, maxLength: 40 }), { minLength: 1, maxLength: 5 })
  .filter((texts) => new Set(texts).size === texts.length)

const questionsFromTextsArb = (texts: string[]): AssessmentQuestion[] =>
  texts.map((text, i) => ({
    questionId: `q_${i + 1}`,
    questionText: text,
    previousScore: 1 + Math.floor(Math.random() * 5), // 1-5; replaced by fc below
    currentScore: 1 + Math.floor(Math.random() * 5),
    targetScore: 4,
    justification: `justification_${i}`,
    attachedEvidenceIds: [],
  }))

// Build a full arbitrary for AssessmentQuestion with distinct question texts per category
const categoryArb = fc
  .tuple(
    uniqueQuestionTextsArb,
    fc.array(
      fc.tuple(scoreArb, scoreArb),
      { minLength: 1, maxLength: 5 },
    ),
    fc.string({ minLength: 1, maxLength: 20 }),
  )
  .map(([texts, scorePairs, catName]): AssessmentCategory => {
    const questions: AssessmentQuestion[] = texts
      .slice(0, scorePairs.length)
      .map((text, i) => ({
        questionId: `q_${i + 1}`,
        questionText: text,
        previousScore: scorePairs[i][0],
        currentScore: scorePairs[i][1],
        targetScore: 4,
        justification: `note_${i}`,
        attachedEvidenceIds: [],
      }))
    return {
      categoryId: `cat_${catName}`,
      categoryName: catName,
      summary: '',
      categoryCurrentAvg: 0, // derived
      categoryTarget: 4,
      questions,
    }
  })

// Category names must be unique within an assessment (they are the session outer keys).
// Also filter out JS prototype-pollution hazard keys (__proto__, constructor, etc.)
// which are not valid category names in practice.
const DANGEROUS_KEYS = new Set(['__proto__', 'constructor', 'prototype'])

const categoriesArb = fc
  .array(categoryArb, { minLength: 1, maxLength: 5 })
  .filter((cats) => {
    const names = cats.map((c) => c.categoryName)
    return (
      new Set(names).size === names.length &&
      names.every((n) => !DANGEROUS_KEYS.has(n))
    )
  })

const assessmentArb = fc
  .record({
    id: fc.string({ minLength: 1, maxLength: 12 }),
    reviewPeriod: fc.string({ minLength: 1, maxLength: 20 }),
    engineerName: fc.string({ minLength: 1, maxLength: 30 }),
    managerName: fc.string({ minLength: 1, maxLength: 30 }),
    categories: categoriesArb,
  })
  .map(({ id, reviewPeriod, engineerName, managerName, categories }): Assessment =>
    withDerivedAverages({
      id,
      dateCompleted: new Date().toISOString(),
      reviewPeriod,
      status: 'Finalized',
      engineerName,
      managerName,
      overallReadinessScore: 0,
      categories,
      oneOnOneTopics: [],
    }),
  )

// ── Properties ────────────────────────────────────────────────────────────────

describe('Property 7 — assessmentToSession / sessionToAssessment round trip', () => {
  it('id, reviewPeriod, engineerName, managerName survive the round trip', () => {
    fc.assert(
      fc.property(assessmentArb, (original) => {
        const session = assessmentToSession(original)
        const restored = sessionToAssessment(session)

        expect(restored.id).toBe(original.id)
        expect(restored.reviewPeriod).toBe(original.reviewPeriod)
        expect(restored.engineerName).toBe(original.engineerName)
        expect(restored.managerName).toBe(original.managerName)
      }),
      { numRuns: 200 },
    )
  })

  it('currentScore (next) survives the round trip for every question', () => {
    fc.assert(
      fc.property(assessmentArb, (original) => {
        const restored = sessionToAssessment(assessmentToSession(original))

        for (const origCat of original.categories) {
          const resCat = restored.categories.find(
            (c) => c.categoryName === origCat.categoryName,
          )
          expect(resCat).toBeDefined()

          for (const origQ of origCat.questions) {
            const resQ = resCat!.questions.find(
              (q) => q.questionText === origQ.questionText,
            )
            expect(resQ).toBeDefined()
            expect(resQ!.currentScore).toBe(origQ.currentScore)
          }
        }
      }),
      { numRuns: 200 },
    )
  })

  it('previousScore (prev) survives the round trip for every question', () => {
    fc.assert(
      fc.property(assessmentArb, (original) => {
        const restored = sessionToAssessment(assessmentToSession(original))

        for (const origCat of original.categories) {
          const resCat = restored.categories.find(
            (c) => c.categoryName === origCat.categoryName,
          )!
          for (const origQ of origCat.questions) {
            const resQ = resCat.questions.find(
              (q) => q.questionText === origQ.questionText,
            )!
            expect(resQ.previousScore).toBe(origQ.previousScore)
          }
        }
      }),
      { numRuns: 200 },
    )
  })

  it('justification (notes) survives the round trip for every question', () => {
    fc.assert(
      fc.property(assessmentArb, (original) => {
        const restored = sessionToAssessment(assessmentToSession(original))

        for (const origCat of original.categories) {
          const resCat = restored.categories.find(
            (c) => c.categoryName === origCat.categoryName,
          )!
          for (const origQ of origCat.questions) {
            const resQ = resCat.questions.find(
              (q) => q.questionText === origQ.questionText,
            )!
            expect(resQ.justification).toBe(origQ.justification)
          }
        }
      }),
      { numRuns: 200 },
    )
  })

  it('questionText (session key) survives the round trip', () => {
    fc.assert(
      fc.property(assessmentArb, (original) => {
        const session = assessmentToSession(original)
        const restored = sessionToAssessment(session)

        const origTexts = original.categories
          .flatMap((c) => c.questions.map((q) => q.questionText))
          .sort()
        const resTexts = restored.categories
          .flatMap((c) => c.questions.map((q) => q.questionText))
          .sort()

        expect(resTexts).toEqual(origTexts)
      }),
      { numRuns: 200 },
    )
  })

  it('category count and names survive the round trip', () => {
    fc.assert(
      fc.property(assessmentArb, (original) => {
        const restored = sessionToAssessment(assessmentToSession(original))
        const origNames = original.categories.map((c) => c.categoryName).sort()
        const resNames = restored.categories.map((c) => c.categoryName).sort()
        expect(resNames).toEqual(origNames)
      }),
      { numRuns: 200 },
    )
  })
})
