/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportRouteImport } from './routes/report'
import { Route as RadarRouteImport } from './routes/radar'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ObjectivesRouteImport } from './routes/objectives'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as InviteRouteImport } from './routes/invite'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as EvidenceRouteImport } from './routes/evidence'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeamEngineerIdRouteImport } from './routes/team.$engineerId'
import { Route as SettingsTeamRouteImport } from './routes/settings.team'
import { Route as SettingsProfileRouteImport } from './routes/settings.profile'
import { Route as SettingsNotificationsRouteImport } from './routes/settings.notifications'
import { Route as SettingsFrameworkRouteImport } from './routes/settings.framework'
import { Route as SettingsExtensionRouteImport } from './routes/settings.extension'
import { Route as SettingsDashboardRouteImport } from './routes/settings.dashboard'
import { Route as TeamEngineerIdTabRouteImport } from './routes/team.$engineerId.$tab'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const RadarRoute = RadarRouteImport.update({
  id: '/radar',
  path: '/radar',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ObjectivesRoute = ObjectivesRouteImport.update({
  id: '/objectives',
  path: '/objectives',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteRoute = InviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidenceRoute = EvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamEngineerIdRoute = TeamEngineerIdRouteImport.update({
  id: '/team/$engineerId',
  path: '/team/$engineerId',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsTeamRoute = SettingsTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsNotificationsRoute = SettingsNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsFrameworkRoute = SettingsFrameworkRouteImport.update({
  id: '/framework',
  path: '/framework',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsExtensionRoute = SettingsExtensionRouteImport.update({
  id: '/extension',
  path: '/extension',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsDashboardRoute = SettingsDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => SettingsRoute,
} as any)
const TeamEngineerIdTabRoute = TeamEngineerIdTabRouteImport.update({
  id: '/$tab',
  path: '/$tab',
  getParentRoute: () => TeamEngineerIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/evidence': typeof EvidenceRoute
  '/feedback': typeof FeedbackRoute
  '/invite': typeof InviteRoute
  '/knowledge': typeof KnowledgeRoute
  '/objectives': typeof ObjectivesRoute
  '/privacy': typeof PrivacyRoute
  '/radar': typeof RadarRoute
  '/report': typeof ReportRoute
  '/settings': typeof SettingsRouteWithChildren
  '/settings/dashboard': typeof SettingsDashboardRoute
  '/settings/extension': typeof SettingsExtensionRoute
  '/settings/framework': typeof SettingsFrameworkRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/team': typeof SettingsTeamRoute
  '/team/$engineerId': typeof TeamEngineerIdRouteWithChildren
  '/team/$engineerId/$tab': typeof TeamEngineerIdTabRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/evidence': typeof EvidenceRoute
  '/feedback': typeof FeedbackRoute
  '/invite': typeof InviteRoute
  '/knowledge': typeof KnowledgeRoute
  '/objectives': typeof ObjectivesRoute
  '/privacy': typeof PrivacyRoute
  '/radar': typeof RadarRoute
  '/report': typeof ReportRoute
  '/settings': typeof SettingsRouteWithChildren
  '/settings/dashboard': typeof SettingsDashboardRoute
  '/settings/extension': typeof SettingsExtensionRoute
  '/settings/framework': typeof SettingsFrameworkRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/team': typeof SettingsTeamRoute
  '/team/$engineerId': typeof TeamEngineerIdRouteWithChildren
  '/team/$engineerId/$tab': typeof TeamEngineerIdTabRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/evidence': typeof EvidenceRoute
  '/feedback': typeof FeedbackRoute
  '/invite': typeof InviteRoute
  '/knowledge': typeof KnowledgeRoute
  '/objectives': typeof ObjectivesRoute
  '/privacy': typeof PrivacyRoute
  '/radar': typeof RadarRoute
  '/report': typeof ReportRoute
  '/settings': typeof SettingsRouteWithChildren
  '/settings/dashboard': typeof SettingsDashboardRoute
  '/settings/extension': typeof SettingsExtensionRoute
  '/settings/framework': typeof SettingsFrameworkRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/team': typeof SettingsTeamRoute
  '/team/$engineerId': typeof TeamEngineerIdRouteWithChildren
  '/team/$engineerId/$tab': typeof TeamEngineerIdTabRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/evidence'
    | '/feedback'
    | '/invite'
    | '/knowledge'
    | '/objectives'
    | '/privacy'
    | '/radar'
    | '/report'
    | '/settings'
    | '/settings/dashboard'
    | '/settings/extension'
    | '/settings/framework'
    | '/settings/notifications'
    | '/settings/profile'
    | '/settings/team'
    | '/team/$engineerId'
    | '/team/$engineerId/$tab'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/evidence'
    | '/feedback'
    | '/invite'
    | '/knowledge'
    | '/objectives'
    | '/privacy'
    | '/radar'
    | '/report'
    | '/settings'
    | '/settings/dashboard'
    | '/settings/extension'
    | '/settings/framework'
    | '/settings/notifications'
    | '/settings/profile'
    | '/settings/team'
    | '/team/$engineerId'
    | '/team/$engineerId/$tab'
  id:
    | '__root__'
    | '/'
    | '/evidence'
    | '/feedback'
    | '/invite'
    | '/knowledge'
    | '/objectives'
    | '/privacy'
    | '/radar'
    | '/report'
    | '/settings'
    | '/settings/dashboard'
    | '/settings/extension'
    | '/settings/framework'
    | '/settings/notifications'
    | '/settings/profile'
    | '/settings/team'
    | '/team/$engineerId'
    | '/team/$engineerId/$tab'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EvidenceRoute: typeof EvidenceRoute
  FeedbackRoute: typeof FeedbackRoute
  InviteRoute: typeof InviteRoute
  KnowledgeRoute: typeof KnowledgeRoute
  ObjectivesRoute: typeof ObjectivesRoute
  PrivacyRoute: typeof PrivacyRoute
  RadarRoute: typeof RadarRoute
  ReportRoute: typeof ReportRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  TeamEngineerIdRoute: typeof TeamEngineerIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/radar': {
      id: '/radar'
      path: '/radar'
      fullPath: '/radar'
      preLoaderRoute: typeof RadarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/objectives': {
      id: '/objectives'
      path: '/objectives'
      fullPath: '/objectives'
      preLoaderRoute: typeof ObjectivesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite': {
      id: '/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof InviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidence': {
      id: '/evidence'
      path: '/evidence'
      fullPath: '/evidence'
      preLoaderRoute: typeof EvidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/$engineerId': {
      id: '/team/$engineerId'
      path: '/team/$engineerId'
      fullPath: '/team/$engineerId'
      preLoaderRoute: typeof TeamEngineerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/team': {
      id: '/settings/team'
      path: '/team'
      fullPath: '/settings/team'
      preLoaderRoute: typeof SettingsTeamRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/notifications': {
      id: '/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof SettingsNotificationsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/framework': {
      id: '/settings/framework'
      path: '/framework'
      fullPath: '/settings/framework'
      preLoaderRoute: typeof SettingsFrameworkRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/extension': {
      id: '/settings/extension'
      path: '/extension'
      fullPath: '/settings/extension'
      preLoaderRoute: typeof SettingsExtensionRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/dashboard': {
      id: '/settings/dashboard'
      path: '/dashboard'
      fullPath: '/settings/dashboard'
      preLoaderRoute: typeof SettingsDashboardRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/team/$engineerId/$tab': {
      id: '/team/$engineerId/$tab'
      path: '/$tab'
      fullPath: '/team/$engineerId/$tab'
      preLoaderRoute: typeof TeamEngineerIdTabRouteImport
      parentRoute: typeof TeamEngineerIdRoute
    }
  }
}

interface SettingsRouteChildren {
  SettingsDashboardRoute: typeof SettingsDashboardRoute
  SettingsExtensionRoute: typeof SettingsExtensionRoute
  SettingsFrameworkRoute: typeof SettingsFrameworkRoute
  SettingsNotificationsRoute: typeof SettingsNotificationsRoute
  SettingsProfileRoute: typeof SettingsProfileRoute
  SettingsTeamRoute: typeof SettingsTeamRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsDashboardRoute: SettingsDashboardRoute,
  SettingsExtensionRoute: SettingsExtensionRoute,
  SettingsFrameworkRoute: SettingsFrameworkRoute,
  SettingsNotificationsRoute: SettingsNotificationsRoute,
  SettingsProfileRoute: SettingsProfileRoute,
  SettingsTeamRoute: SettingsTeamRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

interface TeamEngineerIdRouteChildren {
  TeamEngineerIdTabRoute: typeof TeamEngineerIdTabRoute
}

const TeamEngineerIdRouteChildren: TeamEngineerIdRouteChildren = {
  TeamEngineerIdTabRoute: TeamEngineerIdTabRoute,
}

const TeamEngineerIdRouteWithChildren = TeamEngineerIdRoute._addFileChildren(
  TeamEngineerIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EvidenceRoute: EvidenceRoute,
  FeedbackRoute: FeedbackRoute,
  InviteRoute: InviteRoute,
  KnowledgeRoute: KnowledgeRoute,
  ObjectivesRoute: ObjectivesRoute,
  PrivacyRoute: PrivacyRoute,
  RadarRoute: RadarRoute,
  ReportRoute: ReportRoute,
  SettingsRoute: SettingsRouteWithChildren,
  TeamEngineerIdRoute: TeamEngineerIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
